name: xcube-cci
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - pip
  - aiohttp>=3.6
  - lxml>=4.5
  - pydap >= 3.2
  - oauthlib

  - pip:
    # Required
    - nest_asyncio
    - requests_oauthlib
