name: xcube-cci
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - xcube >= 0.12.1
  - aiohttp >= 3.6
  - gdal >=3.0,<3.6.3
  - lxml >= 4.5
  - nest-asyncio >= 1.3
  - pydap == 3.3
